/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiGroupsRouteImport } from './routes/api/groups'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiImportsRouteImport } from './routes/api/imports'
import { Route as ApiReposRouteImport } from './routes/api/repos'
import { Route as ApiTodosRouteImport } from './routes/api/todos'
import { Route as ApiTokensRouteImport } from './routes/api/tokens'
import { Route as ApiGroupsIdRouteImport } from './routes/api/groups.$id'
import { Route as ApiImportsIdRouteImport } from './routes/api/imports.$id'
import { Route as ApiTodosIdRouteImport } from './routes/api/todos.$id'
import { Route as ApiTokensIdRouteImport } from './routes/api/tokens.$id'
import { Route as ApiTodosIdArchiveRouteImport } from './routes/api/todos.$id.archive'
import { Route as ApiTodosIdMoveRouteImport } from './routes/api/todos.$id.move'
import { Route as ApiTodosIdUnarchiveRouteImport } from './routes/api/todos.$id.unarchive'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGroupsRoute = ApiGroupsRouteImport.update({
  id: '/api/groups',
  path: '/api/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportsRoute = ApiImportsRouteImport.update({
  id: '/api/imports',
  path: '/api/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReposRoute = ApiReposRouteImport.update({
  id: '/api/repos',
  path: '/api/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodosRoute = ApiTodosRouteImport.update({
  id: '/api/todos',
  path: '/api/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokensRoute = ApiTokensRouteImport.update({
  id: '/api/tokens',
  path: '/api/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGroupsIdRoute = ApiGroupsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiGroupsRoute,
} as any)
const ApiImportsIdRoute = ApiImportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiImportsRoute,
} as any)
const ApiTodosIdRoute = ApiTodosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTodosRoute,
} as any)
const ApiTokensIdRoute = ApiTokensIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTokensRoute,
} as any)
const ApiTodosIdArchiveRoute = ApiTodosIdArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => ApiTodosIdRoute,
} as any)
const ApiTodosIdMoveRoute = ApiTodosIdMoveRouteImport.update({
  id: '/move',
  path: '/move',
  getParentRoute: () => ApiTodosIdRoute,
} as any)
const ApiTodosIdUnarchiveRoute = ApiTodosIdUnarchiveRouteImport.update({
  id: '/unarchive',
  path: '/unarchive',
  getParentRoute: () => ApiTodosIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/settings': typeof SettingsRoute
  '/api/groups': typeof ApiGroupsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/imports': typeof ApiImportsRouteWithChildren
  '/api/repos': typeof ApiReposRoute
  '/api/todos': typeof ApiTodosRouteWithChildren
  '/api/tokens': typeof ApiTokensRouteWithChildren
  '/api/groups/$id': typeof ApiGroupsIdRoute
  '/api/imports/$id': typeof ApiImportsIdRoute
  '/api/todos/$id': typeof ApiTodosIdRouteWithChildren
  '/api/tokens/$id': typeof ApiTokensIdRoute
  '/api/todos/$id/archive': typeof ApiTodosIdArchiveRoute
  '/api/todos/$id/move': typeof ApiTodosIdMoveRoute
  '/api/todos/$id/unarchive': typeof ApiTodosIdUnarchiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/settings': typeof SettingsRoute
  '/api/groups': typeof ApiGroupsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/imports': typeof ApiImportsRouteWithChildren
  '/api/repos': typeof ApiReposRoute
  '/api/todos': typeof ApiTodosRouteWithChildren
  '/api/tokens': typeof ApiTokensRouteWithChildren
  '/api/groups/$id': typeof ApiGroupsIdRoute
  '/api/imports/$id': typeof ApiImportsIdRoute
  '/api/todos/$id': typeof ApiTodosIdRouteWithChildren
  '/api/tokens/$id': typeof ApiTokensIdRoute
  '/api/todos/$id/archive': typeof ApiTodosIdArchiveRoute
  '/api/todos/$id/move': typeof ApiTodosIdMoveRoute
  '/api/todos/$id/unarchive': typeof ApiTodosIdUnarchiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/settings': typeof SettingsRoute
  '/api/groups': typeof ApiGroupsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/imports': typeof ApiImportsRouteWithChildren
  '/api/repos': typeof ApiReposRoute
  '/api/todos': typeof ApiTodosRouteWithChildren
  '/api/tokens': typeof ApiTokensRouteWithChildren
  '/api/groups/$id': typeof ApiGroupsIdRoute
  '/api/imports/$id': typeof ApiImportsIdRoute
  '/api/todos/$id': typeof ApiTodosIdRouteWithChildren
  '/api/tokens/$id': typeof ApiTokensIdRoute
  '/api/todos/$id/archive': typeof ApiTodosIdArchiveRoute
  '/api/todos/$id/move': typeof ApiTodosIdMoveRoute
  '/api/todos/$id/unarchive': typeof ApiTodosIdUnarchiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/settings'
    | '/api/groups'
    | '/api/health'
    | '/api/imports'
    | '/api/repos'
    | '/api/todos'
    | '/api/tokens'
    | '/api/groups/$id'
    | '/api/imports/$id'
    | '/api/todos/$id'
    | '/api/tokens/$id'
    | '/api/todos/$id/archive'
    | '/api/todos/$id/move'
    | '/api/todos/$id/unarchive'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/settings'
    | '/api/groups'
    | '/api/health'
    | '/api/imports'
    | '/api/repos'
    | '/api/todos'
    | '/api/tokens'
    | '/api/groups/$id'
    | '/api/imports/$id'
    | '/api/todos/$id'
    | '/api/tokens/$id'
    | '/api/todos/$id/archive'
    | '/api/todos/$id/move'
    | '/api/todos/$id/unarchive'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/logout'
    | '/settings'
    | '/api/groups'
    | '/api/health'
    | '/api/imports'
    | '/api/repos'
    | '/api/todos'
    | '/api/tokens'
    | '/api/groups/$id'
    | '/api/imports/$id'
    | '/api/todos/$id'
    | '/api/tokens/$id'
    | '/api/todos/$id/archive'
    | '/api/todos/$id/move'
    | '/api/todos/$id/unarchive'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SettingsRoute: typeof SettingsRoute
  ApiGroupsRoute: typeof ApiGroupsRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiImportsRoute: typeof ApiImportsRouteWithChildren
  ApiReposRoute: typeof ApiReposRoute
  ApiTodosRoute: typeof ApiTodosRouteWithChildren
  ApiTokensRoute: typeof ApiTokensRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/groups': {
      id: '/api/groups'
      path: '/api/groups'
      fullPath: '/api/groups'
      preLoaderRoute: typeof ApiGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/imports': {
      id: '/api/imports'
      path: '/api/imports'
      fullPath: '/api/imports'
      preLoaderRoute: typeof ApiImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/repos': {
      id: '/api/repos'
      path: '/api/repos'
      fullPath: '/api/repos'
      preLoaderRoute: typeof ApiReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/todos': {
      id: '/api/todos'
      path: '/api/todos'
      fullPath: '/api/todos'
      preLoaderRoute: typeof ApiTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tokens': {
      id: '/api/tokens'
      path: '/api/tokens'
      fullPath: '/api/tokens'
      preLoaderRoute: typeof ApiTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/groups/$id': {
      id: '/api/groups/$id'
      path: '/$id'
      fullPath: '/api/groups/$id'
      preLoaderRoute: typeof ApiGroupsIdRouteImport
      parentRoute: typeof ApiGroupsRoute
    }
    '/api/imports/$id': {
      id: '/api/imports/$id'
      path: '/$id'
      fullPath: '/api/imports/$id'
      preLoaderRoute: typeof ApiImportsIdRouteImport
      parentRoute: typeof ApiImportsRoute
    }
    '/api/todos/$id': {
      id: '/api/todos/$id'
      path: '/$id'
      fullPath: '/api/todos/$id'
      preLoaderRoute: typeof ApiTodosIdRouteImport
      parentRoute: typeof ApiTodosRoute
    }
    '/api/tokens/$id': {
      id: '/api/tokens/$id'
      path: '/$id'
      fullPath: '/api/tokens/$id'
      preLoaderRoute: typeof ApiTokensIdRouteImport
      parentRoute: typeof ApiTokensRoute
    }
    '/api/todos/$id/archive': {
      id: '/api/todos/$id/archive'
      path: '/archive'
      fullPath: '/api/todos/$id/archive'
      preLoaderRoute: typeof ApiTodosIdArchiveRouteImport
      parentRoute: typeof ApiTodosIdRoute
    }
    '/api/todos/$id/move': {
      id: '/api/todos/$id/move'
      path: '/move'
      fullPath: '/api/todos/$id/move'
      preLoaderRoute: typeof ApiTodosIdMoveRouteImport
      parentRoute: typeof ApiTodosIdRoute
    }
    '/api/todos/$id/unarchive': {
      id: '/api/todos/$id/unarchive'
      path: '/unarchive'
      fullPath: '/api/todos/$id/unarchive'
      preLoaderRoute: typeof ApiTodosIdUnarchiveRouteImport
      parentRoute: typeof ApiTodosIdRoute
    }
  }
}

interface ApiGroupsRouteChildren {
  ApiGroupsIdRoute: typeof ApiGroupsIdRoute
}

const ApiGroupsRouteChildren: ApiGroupsRouteChildren = {
  ApiGroupsIdRoute: ApiGroupsIdRoute,
}

const ApiGroupsRouteWithChildren = ApiGroupsRoute._addFileChildren(
  ApiGroupsRouteChildren,
)

interface ApiImportsRouteChildren {
  ApiImportsIdRoute: typeof ApiImportsIdRoute
}

const ApiImportsRouteChildren: ApiImportsRouteChildren = {
  ApiImportsIdRoute: ApiImportsIdRoute,
}

const ApiImportsRouteWithChildren = ApiImportsRoute._addFileChildren(
  ApiImportsRouteChildren,
)

interface ApiTodosIdRouteChildren {
  ApiTodosIdArchiveRoute: typeof ApiTodosIdArchiveRoute
  ApiTodosIdMoveRoute: typeof ApiTodosIdMoveRoute
  ApiTodosIdUnarchiveRoute: typeof ApiTodosIdUnarchiveRoute
}

const ApiTodosIdRouteChildren: ApiTodosIdRouteChildren = {
  ApiTodosIdArchiveRoute: ApiTodosIdArchiveRoute,
  ApiTodosIdMoveRoute: ApiTodosIdMoveRoute,
  ApiTodosIdUnarchiveRoute: ApiTodosIdUnarchiveRoute,
}

const ApiTodosIdRouteWithChildren = ApiTodosIdRoute._addFileChildren(
  ApiTodosIdRouteChildren,
)

interface ApiTodosRouteChildren {
  ApiTodosIdRoute: typeof ApiTodosIdRouteWithChildren
}

const ApiTodosRouteChildren: ApiTodosRouteChildren = {
  ApiTodosIdRoute: ApiTodosIdRouteWithChildren,
}

const ApiTodosRouteWithChildren = ApiTodosRoute._addFileChildren(
  ApiTodosRouteChildren,
)

interface ApiTokensRouteChildren {
  ApiTokensIdRoute: typeof ApiTokensIdRoute
}

const ApiTokensRouteChildren: ApiTokensRouteChildren = {
  ApiTokensIdRoute: ApiTokensIdRoute,
}

const ApiTokensRouteWithChildren = ApiTokensRoute._addFileChildren(
  ApiTokensRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SettingsRoute: SettingsRoute,
  ApiGroupsRoute: ApiGroupsRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiImportsRoute: ApiImportsRouteWithChildren,
  ApiReposRoute: ApiReposRoute,
  ApiTodosRoute: ApiTodosRouteWithChildren,
  ApiTokensRoute: ApiTokensRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
